language: python

python:
  - "3.8"

addons:
  apt:
    packages:
      - x11-utils
      - libxkbcommon-x11-0

services:
  - xvfb

dist:
  - xenial

install:
  - pip install -r requirements.txt
  - pip install pytest-qt pytest-cov

script:
  - pytest -s -v tests
