language: python

python:
  - "3.8"
  
before_install:
  - sudo apt-get install -y x11-utils libxkbcommon-x11-0
        
install:
  - pip install --upgrade pip
  - pip install pyparallel
  - pip install PyQt5
  - pip install PyQtGraph
  - pip install argparse
  - pip install qdarkstyle
  - pip install pytest-qt
  
script:
  - pytest tests
