language: python

python:
  - "3.8"
  
install:
  - pip install --upgrade pip
  - pip install pyparallel
  - pip install PyQt5
  - pip install PyQtGraph
  - pip install argparse
  - pip install qdarkstyle
  - pip install pytest-qt
  
script:
  - pytest tests
