# language: python
# python:
#   - "3.7"

# sudo: required

# before_install:
#   - sudo apt-get update
#   - sudo apt-get install -y xvfb herbstluftwm
#   - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0

# install:
#   - pip install -r requirements.txt
#   - pip install pytest-qt pytest-cov
#   - "export DISPLAY=:99.0"
#   - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
#   - sleep 3

# before_script:
#   - "herbstluftwm &"
#   - sleep 1

# script:
#   - pytest -s -v tests











language: python

python:
  - "3.8"

addons:
  apt:
    packages:
      - x11-utils
      - libxkbcommon-x11-0

services:
  - xvfb

dist:
  - xenial

install:
  - pip install -r requirements.txt
  - pip install pytest-qt pytest-cov

script:
  - pytest -s -v tests
