# Configuration file

# Number of purity monitors
prm_ids: [1, 2, 3]

# PrM 2 is controlled via PrM 1
bound_prms:
  2: 1

prm_id_to_digitizer_type:
  1: 'adpro'
  2: 'adpro'
  3: 'ats310'

prm_id_to_ats_systemid:
  1: None
  2: None
  3: 2

prm_id_to_adpro_channels:
  1: [1, 2]
  2: [3, 4]
  3: None

###################################
# PrM 2 is controlled via PrM 1
# bound_prms:
#   3: 2

# prm_id_to_digitizer_type:
#   1: 'ats310'
#   2: 'adpro'
#   3: 'adpro'

# prm_id_to_ats_systemid:
#   1: 2
#   2: None
#   3: None

# prm_id_to_adpro_channels:
#   1: None
#   2: [1, 2]
#   3: [3, 4]
###################################

# adpro_ip: "192.168.2.10"
adpro_ip: "10.226.35.155"
adpro_username: "digilent"
adpro_password: "digilent"
adpro_port: 8000

data_files_path: '/home/nfs/sbndprm/purity_monitor_data/'
# data_files_path: '/home/nfs/mdeltutt/prm_data/'
# data_files_path: '/sbnd/data/purity_monitors/'
# data_files_path: '/home/nfs/mdeltutt/work/purity_monitors/data/'
# data_files_path: '/Users/mdeltutt/Work/SBND/Purity Monitors/communication/'
save_as_npz: true
save_as_txt: true

arduino_address: '/dev/arduino'
arduino_pin: 7
disable_arduino: False

prm_id_to_mpod_ip:
  1: "10.226.35.154"
  2: "10.226.35.154"
  3: "10.226.35.156"
mpod_prm1_cathode_ch: 100
mpod_prm1_anode_ch: 200
mpod_prm1_anodegrid_ch: 201
mpod_prm2_cathode_ch: 101
mpod_prm2_anode_ch: 202
mpod_prm2_anodegrid_ch: 203
mpod_prm3_cathode_ch: 200
mpod_prm3_anode_ch: 300
mpod_prm3_anodegrid_ch: 301

# Default HV values
prm_hv_default:
  1:
    cathode:   -120
    anode:     4431
    anodegrid: 4351
  2:
    cathode:   -200
    anode:     2408
    anodegrid: 2532
  3:
    cathode:   -120
    anode:     4431
    anodegrid: 4351


# The DAQ will check if the HV is whitin these range
# and will pop a warning if not
prm_hv_ranges:
  1:
    cathode:   [-600, -20]
    anode:     [1000, 6000]
    anodegrid: [1000, 6000]
  2:
    cathode:   [-600, -20]
    anode:     [1000, 6000]
    anodegrid: [1000, 6000]
  3:
    cathode:   [-600, -20]
    anode:     [1000, 6000]
    anodegrid: [1000, 6000]


# Data storage
data_storage: False
data_storage_host: "sbndgpvm01.fnal.gov"
data_storage_username: "sbnd"
data_storage_path: "/exp/sbnd/data/purity_monitors"

