# Configuration file

test: 'test'

prm_id_to_ats_systemid:
  1: 2
  2: 1
  3: 3

data_files_path: '/sbnd/data/purity_monitors/'
# data_files_path: '/home/nfs/mdeltutt/work/purity_monitors/data/'
# data_files_path: '/Users/mdeltutt/Work/SBND/Purity Monitors/communication/'

arduino_address: '/dev/arduino'
# arduino_address: '/dev/cu.usbmodem143301'

arduino_prm1_pin: 7
arduino_prm2_pin: 7
arduino_prm3_pin: 7

mpod_ip: "192.168.0.25"
mpod_prm1_cathode_ch: 100
mpod_prm1_anode_ch: 200
mpod_prm1_anodegrid_ch: 201
mpod_prm2_cathode_ch: 101
mpod_prm2_anode_ch: 202
mpod_prm2_anodegrid_ch: 203
mpod_prm3_cathode_ch: 103
mpod_prm3_anode_ch: 204
mpod_prm3_anodegrid_ch: 205