name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v


      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - run: sudo apt-get install -y x11-utils libxkbcommon-x11-0
      - run: pip install -r requirements.txt
      - run: pip install pytest-qt pytest-cov
      - run: pytest -s -v tests



      # uses: GabrielBB/xvfb-action@v1