name: linux
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: 'x64'
    - name: Install dependencies
      run: |
        sudo apt install -y xvfb x11-utils libxkbcommon-x11-0 libxcb-iccm4
        python -m pip install --upgrade pip
        pip install pyside2 pytest coverage pytest-qt
        pip install -r requirements.txt
        pip install pytest-qt pytest-cov
    - name: Test
      env:
        QT_DEBUG_PLUGINS: 1
      run: xvfb-run pytest -s -v tests
    - run: echo "🍏 This job's status is ${{ job.status }}."
